### ISSUE TITLE
[1.12.2] Cannot open the Aether Accessory Menu.

### ISSUE THREAD

**Issue by SonicX8000** [Henrykado/TheAetherBaubles#4]
Minecraft: 1.12.2
Forge: 14.23.5.2860

Mods:
`aether_baubles-1.0`
`aether-1.12.2-v1.5.3.1`
`Baubles-1.12-1.5.2`
`HadEnoughItems_1.12.2-4.24.6`

You cannot open the Aether Accessory Menu if this mod is installed which can be a problem if you don't have all of the Aether Accessories set to being worn as Baubles.

P.S.
If it's possible, could there be a config option to let you wear the bauble version of the items in the Aether Accessories? Right now with HadEnoughItems there's two versions of the items, one set being the accessories and the other being the baubles. This might be an issue with Had Enough Items, maybe.

...there could also be a possible recipe conflict as you may craft an accessory type instead of a bauble type, or vice versa. A work around could be done by making the accessory type item be crafted into the bauble version and you can recraft it back into the accessory type if you wanted.

![image](https://github.com/Henrykado/TheAetherBaubles/assets/36653806/70b15203-b3e7-4bb2-8fe6-db28960119e1)

**Comment by Henrykado** [comment]
That isn't really possible, mainly because of how the mod works.
I made new baubles versions of each accessory, some of them, when equipped, also equip their original counterparts in the (now hidden) accessory menu. This was done so that certain functionality (like the swet cape making swets friendly) still works.

So, if you were able to open The Aether's accessory menu, you would also be able to get infinite copies of those accessories.

**Comment by Henrykado** [comment]
That isn't really possible, mainly because of how the mod works.
I made new baubles versions of each accessory, some of them, when equipped, also equip their original counterparts in the (now hidden) accessory menu. This was done so that certain functionality (like the swet cape making swets friendly) still works.

So, if you were able to open The Aether's accessory menu, you would also be able to get infinite copies of those accessories.
