### ISSUE TITLE
Instead of options for toggling all gloves, or all misc. Aether baubles, split each item into its own toggle.

### ISSUE THREAD

**Issue by MagmaSlime123** [Henrykado/TheAetherBaubles#8]
Title.

I have several mods which let you do similar stuff to what Lost Content's Invis Gem or Aether's Invis Cape does.
Having each item use its own toggle to selectively remove duplicate content would be nice.

**Comment by Henrykado** [comment]
I removed those options in the latest update of the mod, since it doesn't replace the accessories with new bauble versions of those items anymore, and instead just makes the base wornable as baubles.

So basically i can't remove the items with an option anymore, if you really need to remove items with duplicate abilities for a modpack or something you could always use crafttweaker to remove it's recipe and loottweaker to remove it from loot chests.
